name: cdmi
batch_size: 8
freq: 12H # This is basically meaningless but required by gluonts
device: "cpu"
# Training params
learning_rate: 1E-4
epochs: 25
# Model params
num_layers: 1
num_cells: 40
dropout_rate: 0.1
context_length: 15
num_samples: 50
intervention_type: "knockoff"
error_metric: "mae"
significance_test: "kolmo"
mean_std: 0.05 
step_size: 1
prediction_length: 5
normalize_effect_strength: True
#training split: 
select_automatic_data_split: True 
training_length: 200
num_windows: 10
use_cached_model: False
save_intermediate: False

