defaults:
  - _self_
  - method: var
  - ci_test: ParCorr.yaml
  #- override hydra/launcher: submitit_slurm # Configuration for Multirun on slurm cluster


data_base_path: "sample_datasets/"
ds_name: "no_violation_small" # folder name for datasets
data_path: ${data_base_path}${ds_name}
save_path: "example_saves"
run_name: ${hydra:job.num}
which_dataset: 0 # index of which dataset to use in the folder

verbose: 1

restrict_to_n_samples: -1
restriction_start_index: 0

per_sample_metrics: True
save: True
save_predictions: True

# hydra: # Configuration for Multirun on slurm cluster
#   launcher: 
#     cpus_per_task: 1
#     gpus_per_task: 0
#     mem_gb: 8
#     timeout_min: 2400
#     partition: robolab
